//////////////////////////////////////////////////////////////////////////// - Profile
export const ACTION_CHANGE_INPUT_DATA_ALL = 'ACTION_CHANGE_INPUT_DATA_ALL';
export const ACTION_CHANGE_INPUT_DATA_IMG_SRC = 'ACTION_CHANGE_INPUT_DATA_IMG_SRC';
export const ACTION_CHANGE_INPUT_DATA_TEMPORARY_IMG_SRC = 'ACTION_CHANGE_INPUT_DATA_TEMPORARY_IMG_SRC';
export const ACTION_CHANGE_INPUT_DATA_IMG_CROP_INFO = 'ACTION_CHANGE_INPUT_DATA_IMG_CROP_INFO';
export const ACTION_CHANGE_INPUT_DATA_IMG_SHOW_POPUP = 'ACTION_CHANGE_INPUT_DATA_IMG_SHOW_POPUP';
export const ACTION_CHANGE_INPUT_DATA_IMG_SHOW_POPUP_CROP_WRAPPER = 'ACTION_CHANGE_INPUT_DATA_IMG_SHOW_POPUP_CROP_WRAPPER';
export const ACTION_CHANGE_INPUT_DATA_NAME = 'ACTION_CHANGE_INPUT_DATA_NAME';
export const ACTION_CHANGE_INPUT_DATA_SURNAME = 'ACTION_CHANGE_INPUT_DATA_SURNAME';
export const ACTION_CHANGE_INPUT_DATA_LASTNAME = 'ACTION_CHANGE_INPUT_DATA_LASTNAME';                  // Profile
export const ACTION_CHANGE_INPUT_DATA_SCHOOL = 'ACTION_CHANGE_INPUT_DATA_SCHOOL';
export const ACTION_CHANGE_INPUT_DATA_PHONE_NUMBERS = 'ACTION_CHANGE_INPUT_DATA_PHONE_NUMBERS';
export const ACTION_SAVE_INPUT_DATA_ALL= 'ACTION_SAVE_INPUT_DATA_ALL';
export const ACTION_SAVE_PROFILE_POPUP_SPAN_CLASS= 'ACTION_SAVE_PROFILE_POPUP_SPAN_CLASS';
export const ACTION_SAVE_PROFILE_POPUP_SPAN_TITLE= 'ACTION_SAVE_PROFILE_POPUP_SPAN_TITLE';
//////////////////////////////////////////////////////////////////////////// - Profile

///////////////////////////////////////////////////////////////////////////// - Homework
export const ACTION_CHANGE_HOMEWORK_SHOW_POPUP= 'ACTION_CHANGE_HOMEWORK_SHOW_POPUP';
export const ACTION_CHANGE_HOMEWORK_POPUP_WARNING_TITLE= 'ACTION_CHANGE_HOMEWORK_POPUP_WARNING_TITLE';
export const ACTION_CHANGE_HOMEWORK_POPUP_WARNING_TITLE_CLASS = 'ACTION_CHANGE_HOMEWORK_POPUP_WARNING_TITLE_CLASS';
export const ACTION_CHANGE_HOMEWORK_POPUP_ACTIVE_MENU_ITEM = 'ACTION_CHANGE_HOMEWORK_POPUP_ACTIVE_MENU_ITEM';
export const ACTION_CHANGE_HOMEWORK_CLASSES_LI_LIST = 'ACTION_CHANGE_HOMEWORK_CLASSES_LI_LIST'

export const ACTION_CHANGE_HOMEWORK_REQUESTS_TO_TEACHERS_LI_LIST = 'ACTION_CHANGE_HOMEWORK_REQUESTS_TO_TEACHERS_LI_LIST';
export const ACTION_DELETE_HOMEWORK_REQUESTS_TO_TEACHERS_LI_LIST_ITEM = 'ACTION_DELETE_HOMEWORK_REQUESTS_TO_TEACHERS_LI_LIST_ITEM';

export const ACTION_CHANGE_HOMEWORK_ACCEPTED_TEACHERS_LI_LIST = 'ACTION_CHANGE_HOMEWORK_ACCEPTED_TEACHERS_LI_LIST';
export const ACTION_DELETE_HOMEWORK_ACCEPTED_TEACHERS_LI_LIST_ITEM = 'ACTION_DELETE_HOMEWORK_ACCEPTED_TEACHERS_LI_LIST_ITEM';

export const ACTION_CHANGE_HOMEWORK_STUDENT_REQUESTS_TO_JOIN_LI_LIST = 'ACTION_CHANGE_HOMEWORK_STUDENT_REQUESTS_TO_JOIN_LI_LIST';
export const ACTION_DELETE_HOMEWORK_STUDENT_REQUESTS_TO_JOIN_LI_LIST_ITEM = 'ACTION_DELETE_HOMEWORK_STUDENT_REQUESTS_TO_JOIN_LI_LIST_ITEM';

export const ACTION_CHANGE_HOMEWORK_STUDENTS_IN_CLASS_LI_LIST = "ACTION_CHANGE_HOMEWORK_STUDENTS_IN_CLASS_LI_LIST";
export const ACTION_DELETE_HOMEWORK_STUDENTS_IN_CLASS_LI_LIST_ITEM = 'ACTION_DELETE_HOMEWORK_STUDENTS_IN_CLASS_LI_LIST_ITEM';

export const ACTION_CHANGE_HOMEWORK_STUDENT_START_AND_END_DATE = 'ACTION_CHANGE_HOMEWORK_STUDENT_START_AND_END_DATE';
export const ACTION_CHANGE_HOMEWORK_STUDENT_HOMEWORK_INFO = 'ACTION_CHANGE_HOMEWORK_STUDENT_HOMEWORK_INFO';

export const ACTION_CLEANUP_HOMEWORK_LI_LIST = 'ACTION_CLEANUP_HOMEWORK_LI_LIST';
export const ACTION_CLEAN_HOMEWORK_TEACHERS_LI_LISTS = 'ACTION_CLEAN_HOMEWORK_TEACHERS_LI_LISTS';

///////////////////////////////////////////////////////////////////////////// - Homework

//////////////////////////////////////////////////////////////////////////// - Language
export const ACTION_CHANGE_LANGUAGE= 'ACTION_CHANGE_LANGUAGE';
export const ACTION_CHANGE_LANGUAGE_ACTIVE_CLASS= 'ACTION_CHANGE_LANGUAGE_ACTIVE_CLASS';
export const ACTION_CHANGE_LANGUAGE_FIRST_LABEL= 'ACTION_CHANGE_LANGUAGE_FIRST_LABEL';
export const ACTION_CHANGE_LANGUAGE_SECOND_LABEL= 'ACTION_CHANGE_LANGUAGE_SECOND_LABEL';
//////////////////////////////////////////////////////////////////////////// - Language

//////////////////////////////////////////////////////////////////////////// - SignupReducer
export const ACTION_CHANGE_IS_LOGGED = 'ACTION_CHANGE_IS_LOGGED';
export const ACTION_CHANGE_USER_TYPE = 'ACTION_CHANGE_USER_TYPE';
export const ACTION_CHANGE_IS_FILLED_PROFILE = 'ACTION_CHANGE_IS_FILLED_PROFILE';
//////////////////////////////////////////////////////////////////////////// - SignupReducer

//////////////////////////////////////////////////////////////////////////// - SchoolMarksReducer
export const ACTION_CHANGE_SCHOOL_MARKS_CLASS_LIST = 'ACTION_CHANGE_SCHOOL_MARKS_CLASS_LIST';


//////////////////////////////////////////////////////////////////////////// - SchoolMarksReducer